name: 'george'
version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: g-user
      POSTGRES_PASSWORD: g-pw
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U g-user -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:26.4
    container_name: g-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: g-user
      KC_DB_PASSWORD: g-pw
      KC_SPI_THEME_CACHE_THEMES: "false"
      KC_SPI_THEME_CACHE_TEMPLATES: "false"
    volumes:
      - ./resources/keycloak/keywind.jar:/opt/keycloak/providers/keywind.jar
    command: start-dev
    ports:
      - "8686:8080"
    depends_on:
      - postgres

  bitcoind:
    image: bitcoin/bitcoin:30.2  # Zvanični image
    container_name: bitcoind
    command: [
      "-regtest",
      "-server",
      "-rpcuser=rpc",
      "-rpcpassword=rpc",
      "-rpcallowip=0.0.0.0/0",
      "-rpcbind=0.0.0.0",
      "-rpcport=18443",
      "-port=18444",
      "-fallbackfee=0.0001",
      "-printtoconsole",
      "-whitelist=0.0.0.0/0"
    ]
    ports:
      - "18443:18443"
      - "18444:18444"
    volumes:
      - bitcoin_data:/home/bitcoin/.bitcoin
    healthcheck:
      test: [ "CMD", "bitcoin-cli", "-regtest", "-rpcuser=rpc", "-rpcpassword=rpc", "-rpcport=18443", "getblockchaininfo" ]
      interval: 30s
      timeout: 5s
      retries: 10

  nbxplorer:
    image: nicolasdorier/nbxplorer:2.6.3
    container_name: nbxplorer
    depends_on:
      postgres:
        condition: service_healthy
      bitcoind:
        condition: service_started
    environment:
      NBXPLORER_NETWORK: regtest
      NBXPLORER_BTCRPCURL: "http://bitcoind:18443"
      NBXPLORER_BTCP2PENDPOINT: "bitcoind:18444"
      NBXPLORER_BTCRPCUSER: rpc
      NBXPLORER_BTCRPCPASSWORD: rpc
      NBXPLORER_POSTGRES: "User ID=g-user;Password=g-pw;Host=postgres;Port=5432;Database=nbxplorer;"
      NBXPLORER_BIND: "0.0.0.0"
      NBXPLORER_PORT: 32838
      NBXPLORER_NOAUTH: "true"
    ports:
      - "32838:32838"
    volumes:
      - nbxplorer_data:/datadir
      - ./resources/nbxplorer/regtest.config:/datadir/RegTest/settings.config

  btcpayserver:
    image: btcpayserver/btcpayserver:2.3.7
    container_name: btcpayserver
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "49392:49392"
    environment:
      BTCPAY_NETWORK: regtest
      BTCPAY_BIND: 0.0.0.0
      BTCPAY_PORT: 49392
      BTCPAY_POSTGRES: "User ID=g-user;Password=g-pw;Host=postgres;Port=5432;Database=btcpay;"
      BTCPAY_BTCEXPLORERURL: "http://nbxplorer:32838"
      BTCPAY_ALLOWANYHOST: "true"
      BTCPAY_DISABLE_SSH: "true"
    depends_on:
      postgres:
        condition: service_healthy
      nbxplorer:
        condition: service_started
    volumes:
      - btcpay_data:/datadir

  stalwart-mail:
    image: stalwartlabs/stalwart:latest
    container_name: stalwart-mail
    ports:
      - "25:25"
      - "587:587"
      - "465:465"
      - "143:143"
      - "993:993"
      - "4190:4190"
      - "443:443"
      - "8585:8080"
    volumes:
      - stalwart_data:/opt/stalwart
    tty: true
    stdin_open: true

volumes:
  btcpay_data:
  postgres_data:
  bitcoin_data:
  nbxplorer_data:
  stalwart_data:
