# Server Configuration
server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: george-api

  # Security configuration for OAuth2 Resource Server using JWT
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8686/realms/master}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  # DataSource configuration for PostgreSQL with HikariCP connection pooling
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost:5432}/${DB_NAME:george}?rewriteBatchedStatements=true
    username: ${DB_USERNAME:g-user}
    password: ${DB_PASSWORD:g-pw}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
      leak-detection-threshold: 2000
      # TODO: Consider using auto commit false for better transaction control, but ensure that transactions are properly managed in the application
      # auto-commit: false # Better for transaction control

  # JPA and Hibernate configuration for automatic schema generation and naming strategies
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        multiTenancy: DISCRIMINATOR
        order_updates: true
        order_inserts: true
        batch_versioned_data: true
        jdbc:
          batch_size: 50

  # Flyway configuration for database migrations
  flyway:
    enabled: false
    baseline-on-migrate: true
    validate-on-migrate: true

  # Servlet multipart file upload settings
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB

# API Configuration
api:
  base:
    path: /api/v1
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGIN:http://localhost:4200}

btc-pay:
    store-id: ${BTC_PAY_STORE_ID:5PNvSLGDfwGYgcCWzmsAxAbXLXxqxk2twAtaeMbEdaq6}
    api:
      base-url: ${BTC_PAY_URL:http://localhost:49392/api/v1}
      api-key: ${BTC_PAY_API_KEY:f5c7efdf092c8be1330205a03b5516251c3ef486}


# Logging
logging:
  level:
    org.springframework.web: INFO
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG